plugins {
    id "com.android.application"
}

android {
    namespace "com.homeops.gymtracker"
    compileSdk 36

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.homeops.gymtracker"
        minSdk 26
        targetSdk 36
        versionCode 22
        versionName "1.8-test6"
    }
}

dependencies {
    implementation "androidx.core:core:1.13.1"
    implementation "com.google.android.gms:play-services-nearby:19.3.0"
    implementation "com.google.android.gms:play-services-code-scanner:16.1.0"
    implementation "com.google.zxing:core:3.5.4"
}
